### ISSUE TITLE
India map

### ISSUE THREAD

**Issue by codefromhimanshu** [kadoshms/react-jvectormap#46]
@kadoshms I need to implement India's map with official boundaries as per India's POV.  Also that should be reflected in the world map. The fork of this repo cannot be started.

**Comment by kadoshms** [comment]
@codefromhimanshu what do you mean it cannot be started?

**Comment by codefromhimanshu** [comment]
@kadoshms No worries, I downgraded the webpack version and was able to get it started.

**Comment by joshseltzer** [comment]
Since this issue hasn't been closed yet, I figured I would hijack..

I see that there is a map of India available on jvectormap.com but that it hasn't been added here yet. @codefromhimanshu do you have any estimate of when you might add it here?

@kadoshms perhaps it would be more valuable to write some documentation on how a developer can import the maps files available on jvectormap.com into this plugin, that way we can help port some of the existing maps.

Thanks for the great project! :)

**Comment by kadoshms** [comment]
Done, published in `0.0.16`;

**Comment by kadoshms** [comment]
@joshseltzer you are absolutely right. This project, like some other projects out there, started from a specific need, and started "growing"...
It will be defiantly  great to untie the built in maps from the project, letting everyone use whatever they like. It simply requires some time of refactoring and development, which I hope to have in the near future :)

**Comment by joshseltzer** [comment]
Thanks for your help @kadoshms , and once again thanks for the great project!
