### ISSUE TITLE
jvectormap-tip staying in DOM

### ISSUE THREAD

**Issue by Gunner17** [kadoshms/react-jvectormap#60]
A lot of times I see that the jvectormap-tip is staying in the DOM (screenshot attached), sometimes even showing up although the map has transitioned. It might significantly impact the usability. What is the best way to clean these tooltips? Is there a way to do a manual cleanup? 

<img width="789" alt="Screen Shot 2020-04-23 at 1 23 19 AM" src="https://user-images.githubusercontent.com/11354728/80076653-5a9e3280-8501-11ea-973b-4969cdd64d96.png">

**Comment by lawki** [comment]
The issue seems to be duplicate of https://github.com/kadoshms/react-jvectormap/issues/2

To do manual cleaning do the following when transitioning -

`Array.from(document.getElementsByClassName("jvectormap-tip")).forEach((el) => { el.style.display = "none"; });`

For more details and caveats, see the linked issue https://github.com/kadoshms/react-jvectormap/issues/2

**Comment by Gunner17** [comment]
It helped me! Closing the issue.
